### ISSUE TITLE
STDERR at Row No starting : 32- 40 in cd_template.yaml

### ISSUE THREAD

**Issue by saidreddym** [aws-samples/deploy-kubernetes-resources-to-amazon-eks-using-azure-devops#4]
Hello Team

When we try to deploy the CD using main_template.yaml, we are getting the Error: ##[error]Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream from azure devops pipeline while trying to deploy the 
- task: AWSShellScript@1. Kindly fix the error and confirm us to run the code.

**Comment by asifma** [comment]
Should be solved now.
